### ISSUE TITLE
Framework structure 

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/5-startit-movie-finder-VAbasova#4]
An advice: 
it is better to have strict structure for your framework , and place all tests in one folder "specs":
- it is a common approach among community, so other people will understand your framework faster 
- not critical for now (you have a small amount of code), but in the future, you framework will grow larger, you will have "Page object", "config", "utils", ect. folders, and it will be harder for you find your test files, unless they are in one folder 
- in protractor configuration file it is easier to point what tests you want to run: 
instead of:
```
specs: ['movieCard.ts', 'navigation.ts', 'search.ts', 'lesson5task.ts'],
```  
you can write:
```
specs:['./specs/*.ts']
```

**Comment by VAbasova** [comment]
Fixed
