### ISSUE TITLE
browser.sleep() in searchFor method of home.ts

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/5-startit-movie-finder-VAbasova#5]
```
    async searchFor(search_request: string | number) {
        await this.searchField.sendKeys(search_request, Key.ENTER);
        await browser.sleep(5000);
    }
```
I am sure, that you know why sleep() is not recommended for usage ) 
Also i've seen that you are using explicit waits in other places of you code. Please refactor this method also with explicit waits and ExpectedConditions.

**Comment by VAbasova** [comment]
Fixed
